name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_and_test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # EOL Verisons are excluded here: 21.x
        # Also excluded is versions that don't support node --test: 20.x
        node-version: [22.x, 23.x, 24.x]
        shard: [1/1]
    name: Node v${{matrix.node-version}} on ${{inputs.os}} ${{matrix.shard}}
    runs-on: ${{inputs.os}}
    env:
      CI: true

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run build
      - run:
          DEBUG="testcontainers*" CI=true pnpm run test -- --test-force-exit
          --test-shard ${{matrix.shard}} --test-reporter=spec
          --test-reporter=junit --test-reporter-destination=stdout
          --test-reporter-destination=coverage/junit.xml
        env:
          CI: true

      # - run:
      #     pnpm -r exec -- node --import tsx --test --test-shard=${{ matrix.shard
      #     }} src/__tests__/**/*.test.ts src/__tests__/*.test.ts
