name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        # EOL Verisons are excluded here: 21.x
        # Also excluded is versions that don't support node --test: 20.x
        node-version: [22.x, 23.x, 24.x]
        shard: [1/1]
    name:
      Node v${{ matrix.node-version }} on ${{ inputs.os }} ${{ matrix.shard }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run test -r -- --test-shard ${{ matrix.shard }}

      # - run:
      #     pnpm -r exec -- node --import tsx --test --test-shard=${{ matrix.shard
      #     }} src/__tests__/**/*.test.ts src/__tests__/*.test.ts
